import '../../domain/entities/merchant.dart';
import '../../domain/repositories/merchant_repository.dart';
import '../../../../core/domain/core/result.dart';

/// Use case for completing merchant onboarding.
/// 
/// This use case:
/// - Creates merchant entity
/// - Marks onboarding as complete in user document
/// - Both operations are atomic (handled by repository batch write)
class CompleteMerchantOnboarding {
  const CompleteMerchantOnboarding(this.merchantRepository);

  final MerchantRepository merchantRepository;

  Future<Result<Merchant>> call({
    required String userId,
    required String name,
    required String email,
    required String phone,
    required String city,
    String? address,
    List<String>? categories,
    String? description,
    Map<String, dynamic>? hours,
  }) async {
    // Create merchant entity
    final merchant = Merchant(
      id: '', // Will be generated by repository
      ownerUid: userId,
      name: name,
      email: email,
      phone: phone,
      city: city,
      address: address,
      categories: categories,
      description: description,
      hours: hours,
      status: 'active',
    );

    // Create merchant and link to user (atomic batch write)
    // This also marks onboarding as complete in the same batch
    return await merchantRepository.createMerchantAndLinkUser(
      merchant: merchant,
      userId: userId,
    );
  }
}

