import '../../domain/entities/merchant.dart';
import '../../domain/merchant_failure.dart';
import '../../domain/repositories/merchant_repository.dart';
import '../../../../core/domain/core/result.dart';
import '../../../../core/domain/core/either.dart';

/// Use case for creating a merchant business entity.
/// 
/// This use case:
/// - Validates merchant data
/// - Checks for duplicate merchants
/// - Creates merchant document and links to user atomically
class CreateMerchantUseCase {
  const CreateMerchantUseCase(this._repository);

  final MerchantRepository _repository;

  Future<Result<Merchant>> call({
    required String ownerUid,
    required String name,
    required String email,
    required String phone,
    required String city,
    String? address,
    List<String>? categories,
    String? description,
    Map<String, dynamic>? hours,
  }) async {
    // Validate required fields
    if (ownerUid.isEmpty) {
      return Future<Result<Merchant>>.value(
        const Left<MerchantFailure, Merchant>(
          MerchantUnexpectedFailure(message: 'Owner UID is required.'),
        ),
      );
    }

    if (name.isEmpty) {
      return Future<Result<Merchant>>.value(
        const Left<MerchantFailure, Merchant>(
          MerchantUnexpectedFailure(message: 'Merchant name is required.'),
        ),
      );
    }

    if (email.isEmpty) {
      return Future<Result<Merchant>>.value(
        const Left<MerchantFailure, Merchant>(
          MerchantUnexpectedFailure(message: 'Email is required.'),
        ),
      );
    }

    if (phone.isEmpty) {
      return Future<Result<Merchant>>.value(
        const Left<MerchantFailure, Merchant>(
          MerchantUnexpectedFailure(message: 'Phone number is required.'),
        ),
      );
    }

    if (city.isEmpty) {
      return Future<Result<Merchant>>.value(
        const Left<MerchantFailure, Merchant>(
          MerchantUnexpectedFailure(message: 'City is required.'),
        ),
      );
    }

    // Check if merchant already exists
    final existsResult = await _repository.merchantExists(ownerUid);
    
    return existsResult.fold(
      (failure) => Left<MerchantFailure, Merchant>(
        failure is MerchantFailure
            ? failure
            : MerchantUnexpectedFailure(
                message: failure.message,
                cause: failure.cause,
                stackTrace: failure.stackTrace,
              ),
      ),
      (exists) async {
        if (exists) {
          return const Left<MerchantFailure, Merchant>(
            MerchantAlreadyExistsFailure(),
          );
        }

        // Generate merchant ID (will be handled by repository in actual implementation)
        // For now, we'll let the repository generate it
        final merchant = Merchant(
          id: '', // Will be generated by repository
          ownerUid: ownerUid,
          name: name,
          email: email,
          phone: phone,
          city: city,
          address: address,
          categories: categories,
          description: description,
          hours: hours,
          status: 'active',
        );

        // Create merchant and link to user atomically
        return await _repository.createMerchantAndLinkUser(
          merchant: merchant,
          userId: ownerUid,
        );
      },
    );
  }
}

