/// List of major French cities for city picker
const List<String> frenchCities = [
  'Paris',
  'Lyon',
  'Marseille',
  'Toulouse',
  'Nice',
  'Nantes',
  'Strasbourg',
  'Montpellier',
  'Bordeaux',
  'Lille',
  'Rennes',
  'Reims',
  'Saint-Étienne',
  'Toulon',
  'Le Havre',
  'Grenoble',
  'Dijon',
  'Angers',
  'Nîmes',
  'Villeurbanne',
  'Saint-Denis',
  'Le Mans',
  'Aix-en-Provence',
  'Clermont-Ferrand',
  'Brest',
  'Limoges',
  'Tours',
  'Amiens',
  'Perpignan',
  'Metz',
  'Besançon',
  'Boulogne-Billancourt',
  'Orléans',
  'Mulhouse',
  'Caen',
  'Rouen',
  'Nancy',
  'Argenteuil',
  'Montreuil',
  'Saint-Paul',
];

