// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvsKq-3-HFXR7ODyIUfVDlMlYlWavu25U',
    appId: '1:20266054150:android:9761ea41e69fc9295a4987',
    messagingSenderId: '20266054150',
    projectId: 'yuztoo',
    storageBucket: 'yuztoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk9okSTdsXuVCvn69TB3xnq6wU9KV_mro',
    appId: '1:20266054150:ios:a17342947aacce925a4987',
    messagingSenderId: '20266054150',
    projectId: 'yuztoo',
    storageBucket: 'yuztoo.firebasestorage.app',
    androidClientId: '20266054150-912h7gr3gfm6u8r2looddsk8qq8ttojn.apps.googleusercontent.com',
    iosClientId: '20266054150-omm1tiu719qq6rkbpvm6q5sposih75af.apps.googleusercontent.com',
    iosBundleId: 'com.yuztoo.app',
  );

}