enum UserRole { client, merchant }

enum ScreenId {
  splash,
  roleSelection,
  login,
  signup,
  otp,
  clientHome,
  discovery,
  qrScanner,
  loyalty,
  storeProfile,
  notifications,
  messages,
  clientProfile,
  merchantOnboarding,
  merchantSubcategorySelection,
  merchantBenefits,
  merchantDashboard,
  merchantClients,
  merchantPromotions,
  merchantQr,
  merchantMessages,
  merchantProfile,
  merchantStats,
  merchantStorefront,
  merchantRappels,
  merchantNotificationsAuto,
  merchantEFidelite,
  merchantAccountPreferences,
}
